[pytest]
minversion = 7.0
testpaths = tests
addopts = -q
norecursedirs =
    .* 
    build
    dist
    __pycache__
    .venv
    .tox
    src/CustomBoostTrack/external
    src/CustomBoostTrack/weights
    var
