from flask import Flask, render_template, request, jsonify, url_for, send_from_directory
import os
import uuid
import json
from werkzeug.utils import secure_filename
import threading

app = Flask(__name__)
app.config['UPLOAD_FOLDER'] = 'app/uploads'
app.config['RESULTS_FOLDER'] = 'app/results'
app.config['MAX_CONTENT_LENGTH'] = 500 * 1024 * 1024  # 500MB max upload size
app.config['ALLOWED_EXTENSIONS'] = {'mp4', 'avi', 'mov', 'mkv'}

# Ensure directories exist
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)
os.makedirs(app.config['RESULTS_FOLDER'], exist_ok=True)

# Processing status dictionary
processing_status = {}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in app.config['ALLOWED_EXTENSIONS']

def process_video(video_path, result_id):
    """
    Process the uploaded video with the tracking pipeline.
    This is a placeholder for the actual tracking implementation.
    """
    try:
        processing_status[result_id] = {'status': 'processing'}
        
        # TODO: Replace with actual tracking pipeline call
        # This is where you would call your existing tracking pipeline
        # For now, we'll simulate processing with a delay
        import time
        time.sleep(5)  # Simulate processing time
        
        # Create results directory for this upload
        result_dir = os.path.join(app.config['RESULTS_FOLDER'], result_id)
        os.makedirs(result_dir, exist_ok=True)
        
        # Simulate creating annotated video (in real implementation, this would be done by the tracking pipeline)
        # For now, just copy the original video
        import shutil
        annotated_video_path = os.path.join(result_dir, 'annotated_video.mp4')
        shutil.copy(video_path, annotated_video_path)
        
        # Create dummy annotations (in real implementation, these would be generated by the tracking pipeline)
        annotations = {
            "1": [{"x": 100, "y": 100, "width": 50, "height": 50, "id": 1}],
            "2": [{"x": 120, "y": 120, "width": 50, "height": 50, "id": 1}],
            "3": [{"x": 140, "y": 140, "width": 50, "height": 50, "id": 1}]
        }
        
        # Save annotations to file
        with open(os.path.join(result_dir, 'annotations.json'), 'w') as f:
            json.dump(annotations, f)
        
        processing_status[result_id] = {'status': 'completed'}
        
    except Exception as e:
        processing_status[result_id] = {'status': 'failed', 'error': str(e)}
        print(f"Error processing video: {e}")

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/upload', methods=['POST'])
def upload_video():
    if 'video' not in request.files:
        return jsonify({'status': 'error', 'message': 'No video file found'}), 400
    
    file = request.files['video']
    
    if file.filename == '':
        return jsonify({'status': 'error', 'message': 'No video selected'}), 400
    
    if file and allowed_file(file.filename):
        # Generate a unique ID for this upload
        result_id = str(uuid.uuid4())
        
        # Save the uploaded file
        filename = secure_filename(file.filename)
        video_path = os.path.join(app.config['UPLOAD_FOLDER'], f"{result_id}_{filename}")
        file.save(video_path)
        
        # Start processing in a separate thread
        processing_thread = threading.Thread(
            target=process_video, 
            args=(video_path, result_id)
        )
        processing_thread.start()
        
        return jsonify({
            'status': 'success',
            'message': 'Video uploaded successfully. Processing started.',
            'result_id': result_id
        })
    
    return jsonify({'status': 'error', 'message': 'File type not allowed'}), 400

@app.route('/results/<result_id>/status')
def get_status(result_id):
    if result_id in processing_status:
        return jsonify(processing_status[result_id])
    return jsonify({'status': 'not_found'}), 404

@app.route('/results/<result_id>/video')
def get_video(result_id):
    result_dir = os.path.join(app.config['RESULTS_FOLDER'], result_id)
    return send_from_directory(result_dir, 'annotated_video.mp4')

@app.route('/results/<result_id>/annotations')
def get_annotations(result_id):
    result_dir = os.path.join(app.config['RESULTS_FOLDER'], result_id)
    return send_from_directory(result_dir, 'annotations.json')

if __name__ == '__main__':    
    app.run(debug=True, ssl_context='adhoc') 